site_name: NEM Library
nav:
  - Home: 'index.md'
  - Documentation:
    - 'documentation/architecture.md'
    - 'documentation/overview.md'
    - 'documentation/connection_pool.md'
    - 'documentation/account.md'
    - 'documentation/transaction.md'
    - 'documentation/namespace.md'
    - 'documentation/mosaic.md'
    - 'documentation/node.md'
    - 'documentation/blockchain.md'
    - 'documentation/listener.md'
    - 'documentation/wallet.md'
    - 'documentation/service.md'
    - 'documentation/error.md'

  - Guide:
    - 'guide/overview.md'
    - 'guide/account.md'
    - 'guide/transaction.md'
    - 'guide/namespace.md'
    - 'guide/mosaic.md'
    - 'guide/node.md'
    - 'guide/blockchain.md'
    - 'guide/listener.md'
    - 'guide/wallet.md'

  - Support: 'support.md'
  - Internal Development Process: 'internal_development_process.md'
  - About: 'about.md'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - typescript
        - json
repo_url: https://github.com/aleixmorgadas/nem-library-docs/
site_url: https://nemlibrary.com
site_description: NEM Library Documentation for NEM Blockchain.
extra_css: [extra.css]
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde