site_name: NEM Library
pages:
  - Home: 'index.md'
  - Documentation:
    - 'documentation/architecture.md'
    - 'documentation/overview.md'
    - 'documentation/account.md'
    - 'documentation/transaction.md'
    - 'documentation/namespace.md'
    - 'documentation/mosaic.md'
    - 'documentation/node.md'
    - 'documentation/block.md'
    - 'documentation/chain.md'
  - Guide:
    - 'guide/overview.md'
    - 'guide/account.md'
    - 'guide/transaction.md'
    - 'guide/namespace.md'
    - 'guide/mosaic.md'
    - 'guide/node.md'
    - 'guide/block.md'
    - 'guide/chain.md'
  - Support: 'support.md'
  - Development process: 'development_process.md'
  - Roadmap: 'roadmap.md'
  - About: 'about.md'
theme: readthedocs
repo_url: https://github.com/aleixmorgadas/nem-library-docs/
site_description: NEM Library Documentation for NEM Blockchain.
google_analytics: ['UA-83164077-5', 'mkdocs.org']

