site_name: NEM Library
pages:
  - Home: 'index.md'
  - Documentation:
    - 'documentation/architecture.md'
    - 'documentation/overview.md'
    - 'documentation/account.md'
    - 'documentation/transaction.md'
    - 'documentation/namespace.md'
    - 'documentation/mosaic.md'
    - 'documentation/custom_mosaics.md'
    - 'documentation/node.md'
    - 'documentation/blockchain.md'
    - 'documentation/listener.md'
    - 'documentation/wallet.md'
    - 'documentation/service.md'
    - 'documentation/error.md'

  - Guide:
    - 'guide/overview.md'
    - 'guide/account.md'
    - 'guide/transaction.md'
    - 'guide/namespace.md'
    - 'guide/mosaic.md'
    - 'guide/node.md'
    - 'guide/blockchain.md'
    - 'guide/listener.md'
    - 'guide/wallet.md'

  - Support: 'support.md'
  - Internal Development Process: 'internal_development_process.md'
  - Roadmap: 'roadmap.md'
  - About: 'about.md'
theme: readthedocs
repo_url: https://github.com/aleixmorgadas/nem-library-docs/
site_url: https://nemlibrary.com
site_description: NEM Library Documentation for NEM Blockchain.
google_analytics: ['UA-83164077-5', 'nemlibrary.com']

