site_name: NEM Library
pages:
  - Home: 'index.md'
  - Documentation:
    - 'documentation/architecture.md'
    - 'documentation/blockchain.md'
    - 'documentation/node.md'
    - 'documentation/account.md'
    - 'documentation/namespace.md'
    - 'documentation/mosaic.md'
    - 'documentation/transaction.md'
  - Support: 'support.md'
  - Roadmap: 'roadmap.md'
  - About: 'about.md'
theme: readthedocs
repo_url: https://github.com/aleixmorgadas/nem-library-docs/
site_description: NEM Library Documentation for NEM Blockchain.
google_analytics: ['UA-83164077-5', 'mkdocs.org']

